version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: municollect_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d municollect_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: